version: '3'
services:
  app:
    build: .
    environment:
      HTTP_PORT: ${HTTP_PORT}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    command: sh -c "/wait-for-it db:5432 -- modd"
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
  db:
    image: postgres
    environment:
      POSTGRES_DB: expense-tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
