version: '3'
services:
  client:
    build: ./client
    container_name: expensetracker_client
    environment:
      SERVER_API_URL: http://server:${SERVER_PORT}
    volumes:
      - ./client:/app
    command: sh -c "npm install && quasar dev"
    ports:
      - '8080:8080'
    depends_on:
      - 'server'
  server:
    build: ./server
    container_name: expensetracker_server
    environment:
      PORT: ${SERVER_PORT}
      JWT_PRIVATE_KEY: ${SERVER_JWT_PRIVATE_KEY}
      DATABASE_URL: ${SERVER_DATABASE_URL}
    volumes:
      - ./server:/app
    command: sh -c "/wait-for-it db:5432 -- modd"
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - 'db'
  db:
    image: postgres
    container_name: expensetracker_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
